"""The hand-written seed roster.

Order in this list is meaningless - the stack is always sorted by score.
p_amara is the profile the demo script walks through; DEMO_USER is the Demo fill.
"""

def S(name, level="solid"):
    return {"name": name, "level": level}


DEMO_USER = {
    "id": "me",
    "name": "Donny",
    "school": "MIT",
    "avatar": "nova",
    "skills": [
        S("Frontend", "expert"),
        S("Product design"),
        S("Product management"),
        S("Writing / Content", "learning"),
    ],
    "missing": ["Backend", "Data"],
    "want_to_build": "Campus tools people actually use. Right now: which dining halls are actually crowded, live, so nobody walks across campus into a 40-minute line.",
    "commitment": "side_project",
    "experience": "shipped",
    "team_size": "2",
    "prompts": {
        "hackathon_person": "...who has the landing page done before we agree on the idea",
        "toxic_trait": "I will redesign the whole screen at 3am and call it a small tweak",
        "excited_about": "any campus system with a public API",
    },
    # Demo fill supplies its own identity line; real users get a generated one.
    "builder_title": "Frontend builder obsessed with making campus tools people actually use",
    "github": None,
}

# Seeded, hand-written "Why you two" for the demo user's strongest pairs. These
# are what the rail, Discover and profile pages show instead of a template.
# Each is grounded in the two profiles' actual fields. Amara's lives in
# ai/fallbacks.py so the offline path and the seed stay identical.
DEMO_REASONS = {
    "p_lin": (
        "Lin has the Data you're missing and the infra habits you skip, and your Frontend and "
        "Product design are the two things her energy tool has never had. You're both after the "
        "one number that changes what people do - she digs it out of utility data, you pull it "
        "off the dining line."
    ),
    "p_nadia": (
        "Nadia is making a decade of unreadable lab notebooks searchable; you're trying to make a "
        "40 MB campus map usable. Same obsession with data nobody can read, and she has the ML "
        "and Data you don't while you have the Frontend her search has been waiting for."
    ),
    "p_maya": (
        "Maya has the Data and Backend you're missing, and you have the Frontend and Product "
        "design her tutor has been running without. You both build for students who drop a tool "
        "the second it lies to them - her tutor, your crowd meter."
    ),
    "p_arjun": (
        "Arjun has the Backend you're missing and deploys on Fridays without flinching; your "
        "Frontend and Product design are exactly what his infra tools have never had. He builds "
        "for two-person teams that ship every week, which is the team you'd be."
    ),
    "p_sarah": (
        "Sarah is missing the same Backend and Data you are, so this isn't a skills fit - it's a "
        "shared obsession. She wants neighbors to actually show up for each other, you want campus "
        "to actually work for the people on it, and Block Board needs her design and community "
        "instincts."
    ),
}

# The demo user's own seeded content. Only visible while the Demo fill profile
# is the active user; a real user never inherits it.
DEMO_PROJECT = {
    "id": "proj_dining",
    "name": "Dining Rush",
    "one_liner": "Which dining halls are actually crowded right now.",
    "team_ids": ["me"],
    "has": ["Frontend", "Product design"],
    "needs": ["Backend"],
    "stage": "prototype",
    "tags": ["campus", "realtime"],
    "updates": ["po_d1", "po_d3"],
    "demo": True,
}

DEMO_POSTS = [
    {"id": "po_d1", "type": "update", "hours_ago": 4, "project_id": "proj_dining",
     "text": "trying to ship a little app this weekend that shows which dining halls are actually crowded. terrible at backend though lol"},
    {"id": "po_d2", "type": "update", "hours_ago": 20, "project_id": None,
     "text": "campus map is 40mb for reasons no one can explain to me."},
    {"id": "po_d3", "type": "build_log", "hours_ago": 44, "project_id": "proj_dining",
     "text": "dining hall crowd meter v0 is a google form and a group text. it's embarrassing and 60 people use it."},
]

# Kept for anything that still imports the old name.
ALEX = DEMO_USER

ROSTER = [
    {
        "id": "p_maya",
        "name": "Maya Okafor",
        "school": "Harvard",
        "avatar": "juno",
        "skills": [S("ML / AI", "expert"), S("Data"), S("Backend", "learning")],
        "missing": ["Frontend", "Product design"],
        "want_to_build": "Consumer AI that admits when it's wrong. Right now that's a tutor that explains things confidently and incorrectly.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who retrains the model at 3am and somehow it's better",
            "toxic_trait": "I will fight you over an eval metric",
            "excited_about": "small vision models that run on a phone",
        },
        "builder_title": "ML person building consumer AI that admits mistakes",
    },
    {
        "id": "p_dev",
        "name": "Dev Malhotra",
        "school": "Berklee x Northeastern",
        "avatar": "ember",
        "skills": [S("Frontend", "expert"), S("Music production", "expert"), S("Visual design")],
        "missing": ["Backend", "ML / AI"],
        "want_to_build": "A social feed where producers drop 8-bar loops and strangers finish them in public.",
        "commitment": "side_project",
        "experience": "founded",
        "team_size": "3-4",
        "prompts": {
            "hackathon_person": "...who ships a landing page before we have a product",
            "toxic_trait": "I will start a Discord for a project with two people in it",
            "excited_about": "watching someone hear their own loop come back finished",
        },
        "builder_title": "Frontend producer building an audience first",
    },
    {
        "id": "p_sofia",
        "name": "Sofia Marchetti",
        "school": "RISD",
        "avatar": "pixel",
        "skills": [S("Product design", "expert"), S("Motion / 3D", "expert"), S("Frontend")],
        "missing": ["Backend", "Data"],
        "want_to_build": "Visual tools that make music theory feel like a video game instead of homework.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who makes the one animation everyone screenshots",
            "toxic_trait": "nothing ships until the easing curve is right",
            "excited_about": "the exact moment a chord finally makes sense to someone",
        },
        "builder_title": "Motion designer teaching music by making it move",
    },
    {
        "id": "p_priya",
        "name": "Priya Raghunathan",
        "school": "MIT",
        "avatar": "koda",
        "skills": [S("Hardware / Embedded", "expert"), S("ML / AI"), S("Systems / Low-level")],
        "missing": ["Mobile (iOS)", "Product design"],
        "want_to_build": "Assistive hardware people would actually wear. A haptic glove that navigates for you, cheap enough to give away.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who brought hardware to a software hackathon and made it everyone's problem",
            "toxic_trait": "I will rewire the thing you asked me to mock up",
            "excited_about": "accessibility and computer vision, together",
        },
        "builder_title": "Hardware person building assistive tech people would wear",
    },
    {
        "id": "p_kai",
        "name": "Kai Tanaka",
        "school": "Berklee",
        "avatar": "wren",
        "skills": [S("Music production", "expert"), S("Community", "expert"), S("Writing / Content")],
        "missing": ["Backend", "Frontend", "Product design"],
        "want_to_build": "A weekly thing where four strangers have to release one song together by Sunday.",
        "commitment": "hackathon",
        "experience": "first_hackathon",
        "team_size": "any",
        "prompts": {
            "hackathon_person": "...who feeds everyone and somehow knows all the judges",
            "toxic_trait": "I say yes to every collab and then I have nine collabs",
            "excited_about": "deadlines, genuinely, they're the only reason anything exists",
        },
        "builder_title": "Producer who runs on deadlines and strangers",
    },
    {
        "id": "p_zoe",
        "name": "Zoe Feldman",
        "school": "Olin",
        "avatar": "nova",
        "skills": [S("Hardware / Embedded", "expert"), S("Systems / Low-level"), S("Music production")],
        "missing": ["Frontend", "Visual design"],
        "want_to_build": "Modular synth gear that costs forty dollars instead of four hundred.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who brought a soldering iron and a multimeter, just in case",
            "toxic_trait": "I will breadboard the thing you asked me to mock up",
            "excited_about": "cheap DACs that have no business sounding that good",
        },
        "builder_title": "Hardware person making synths people can afford",
    },
    {
        "id": "p_finn",
        "name": "Finn Gallagher",
        "school": "Berklee",
        "avatar": "juno",
        "skills": [S("Video", "expert"), S("Music production"), S("Marketing / Growth")],
        "missing": ["Frontend", "Backend"],
        "want_to_build": "Short films scored by people who have never met the director.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "3-4",
        "prompts": {
            "hackathon_person": "...who is filming all of this for a recap nobody asked for",
            "toxic_trait": "I'll reshoot something that was already fine",
            "excited_about": "the three seconds before a cut lands right",
        },
        "builder_title": "Video person scoring films with strangers",
    },
    {
        "id": "p_jonas",
        "name": "Jonas Weber",
        "school": "BU",
        "avatar": "pixel",
        "skills": [S("Product design", "expert"), S("Frontend", "expert"), S("UX research")],
        "missing": ["Backend", "Data"],
        "want_to_build": "Compliance tooling so small fintech startups stop getting sued over things nobody explained to them.",
        "commitment": "cofounder",
        "experience": "founded",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who has already made the pitch deck",
            "toxic_trait": "I turn every conversation into a roadmap",
            "excited_about": "boring software that saves someone their entire week",
        },
        "builder_title": "Designer making compliance survivable for tiny startups",
    },
    {
        "id": "p_isla",
        "name": "Isla Brennan",
        "school": "RISD",
        "avatar": "ember",
        "skills": [S("Visual design", "expert"), S("Product design"), S("Marketing / Growth")],
        "missing": ["Backend", "Mobile (iOS)"],
        "want_to_build": "A way for independent fashion designers to find manufacturers who take runs of thirty.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who names the project and suddenly everyone believes in it",
            "toxic_trait": "I redo the logo the night before demos",
            "excited_about": "small factories that still answer the phone",
        },
        "builder_title": "Visual designer connecting makers to small factories",
    },
    {
        "id": "p_amara",
        "name": "Amara Boateng",
        "school": "Wellesley",
        "avatar": "koda",
        "skills": [S("Data", "expert"), S("Backend"), S("Writing / Content")],
        "missing": ["Frontend", "Product design"],
        "want_to_build": "Something that shows people what their bus commute actually did this month versus the posted schedule.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who found the dataset nobody knew was public",
            "toxic_trait": "I will spend four hours on a chart axis",
            "excited_about": "city data that quietly proves someone wrong",
        },
        "builder_title": "Data person holding the city bus accountable",
    },
    {
        "id": "p_theo",
        "name": "Theo Lindqvist",
        "school": "Olin",
        "avatar": "wren",
        "skills": [S("Hardware / Embedded", "expert"), S("Game dev"), S("Motion / 3D")],
        "missing": ["Backend", "Marketing / Growth"],
        "want_to_build": "Physical controllers for games that currently only exist on a keyboard.",
        "commitment": "hackathon",
        "experience": "shipped",
        "team_size": "3-4",
        "prompts": {
            "hackathon_person": "...whose demo requires a table, an outlet and a prayer",
            "toxic_trait": "I'll 3D print a case for something that has no circuit yet",
            "excited_about": "the click of a good mechanical switch",
        },
        "builder_title": "Hardware person building controllers games don't have",
    },
    {
        "id": "p_lin",
        "name": "Lin Zhao",
        "school": "Northeastern",
        "avatar": "nova",
        "skills": [S("Data", "expert"), S("ML / AI"), S("DevOps / Infra")],
        "missing": ["Product design", "Frontend"],
        "want_to_build": "A tool that tells a household the one change actually worth making to their energy bill.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who set up CI at hour two and everyone laughed until hour twenty",
            "toxic_trait": "I will containerize a script",
            "excited_about": "utility data, which is somehow both public and unusable",
        },
        "builder_title": "Data person finding the one change worth making",
    },
    {
        "id": "p_ruby",
        "name": "Ruby Castellanos",
        "school": "RISD",
        "avatar": "juno",
        "skills": [S("Motion / 3D", "expert"), S("Game dev", "expert"), S("Visual design")],
        "missing": ["Backend", "Systems / Low-level"],
        "want_to_build": "A two-player game that falls apart unless both people are actually talking.",
        "commitment": "hackathon",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who builds the whole thing around one weird mechanic",
            "toxic_trait": "I'll animate a menu nobody will open",
            "excited_about": "games where the other person is the controller",
        },
        "builder_title": "Game designer making people talk to each other",
    },
    {
        "id": "p_omar",
        "name": "Omar Haddad",
        "school": "MIT",
        "avatar": "pixel",
        "skills": [S("Systems / Low-level", "expert"), S("Backend", "expert"), S("Security")],
        "missing": ["Product design", "Marketing / Growth"],
        "want_to_build": "A local-first database that survives a laptop dying mid-write, for people who don't trust the cloud.",
        "commitment": "cofounder",
        "experience": "founded",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who is reading the spec, the actual spec, the PDF one",
            "toxic_trait": "I will tell you your abstraction is wrong and I'll be right",
            "excited_about": "crash recovery, write-ahead logs, things nobody thanks you for",
        },
        "builder_title": "Systems person building storage that survives anything",
    },
    {
        "id": "p_nadia",
        "name": "Nadia Petrova",
        "school": "Harvard",
        "avatar": "ember",
        "skills": [S("ML / AI", "expert"), S("Data"), S("Writing / Content")],
        "missing": ["Frontend", "Product design"],
        "want_to_build": "Tools that let a wet lab search its own decade of messy notebooks.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who read the paper the project is based on, twice",
            "toxic_trait": "I'll ask what your baseline is and ruin the mood",
            "excited_about": "search that works on handwriting from 2013",
        },
        "builder_title": "ML person making old lab notebooks searchable",
    },
    {
        "id": "p_elena",
        "name": "Elena Rossi",
        "school": "Wellesley",
        "avatar": "koda",
        "skills": [S("UX research", "expert"), S("Product design"), S("Writing / Content")],
        "missing": ["Backend", "Frontend", "Data"],
        "want_to_build": "Something that keeps track of what actually changed for a patient between two appointments.",
        "commitment": "side_project",
        "experience": "first_hackathon",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who talks to six real users while everyone else argues",
            "toxic_trait": "I will keep asking why until you're annoyed",
            "excited_about": "the gap between what people say and what they do",
        },
        "builder_title": "Researcher tracking what changes between appointments",
    },
    {
        "id": "p_marcus",
        "name": "Marcus Webb",
        "school": "Georgia Tech",
        "avatar": "wren",
        "skills": [S("Game dev", "expert"), S("Systems / Low-level"), S("Backend")],
        "missing": ["Visual design", "Motion / 3D", "Marketing / Growth"],
        "want_to_build": "A tiny engine that lets players build levels without ever seeing code.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who has a working prototype at hour four and a rewrite at hour twenty",
            "toxic_trait": "I'll write my own engine rather than learn yours",
            "excited_about": "frame budgets and the hunt for a stolen millisecond",
        },
        "builder_title": "Game dev handing level design to players",
    },
    {
        "id": "p_yuki",
        "name": "Yuki Sato",
        "school": "Waterloo",
        "avatar": "nova",
        "skills": [S("Mobile (iOS)", "expert"), S("Frontend"), S("Product design")],
        "missing": ["Backend", "ML / AI"],
        "want_to_build": "An app that gives you one honest question a day and no feed to scroll.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who has it running on a real phone before anyone else has a repo",
            "toxic_trait": "I'll delete a feature you liked because it felt heavy",
            "excited_about": "apps small enough to explain in one sentence",
        },
        "builder_title": "iOS dev building apps with nothing to scroll",
    },
    {
        "id": "p_tess",
        "name": "Tess O'Halloran",
        "school": "BU",
        "avatar": "juno",
        "skills": [S("Writing / Content", "expert"), S("Marketing / Growth", "expert"), S("Community")],
        "missing": ["Frontend", "Backend", "Product design"],
        "want_to_build": "A newsletter product for people who know one thing deeply and have never written it down.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who writes the demo script and saves everyone at minute fifty-eight",
            "toxic_trait": "I'll rename the project four times before lunch",
            "excited_about": "the first paragraph, which is the only hard one",
        },
        "builder_title": "Writer getting quiet experts to publish",
    },
    {
        "id": "p_arjun",
        "name": "Arjun Nair",
        "school": "MIT",
        "avatar": "pixel",
        "skills": [S("DevOps / Infra", "expert"), S("Backend", "expert"), S("Security")],
        "missing": ["Product design", "Visual design", "Frontend"],
        "want_to_build": "Deploy tooling for two-person teams who ship weekly and hate configuring anything.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who has staging up before the idea is settled",
            "toxic_trait": "I'll add a health check to a weekend project",
            "excited_about": "deploys boring enough to do on a Friday",
        },
        "builder_title": "Infra person making deploys boring for two-person teams",
    },
    {
        "id": "p_ade",
        "name": "Adewale Johnson",
        "school": "Northeastern",
        "avatar": "ember",
        "skills": [S("Security", "expert"), S("Backend"), S("Systems / Low-level")],
        "missing": ["Frontend", "Product design", "Writing / Content"],
        "want_to_build": "A scanner that tells student projects which one of their secrets is already on GitHub.",
        "commitment": "hackathon",
        "experience": "shipped",
        "team_size": "3-4",
        "prompts": {
            "hackathon_person": "...who finds the exposed key in someone else's demo, politely",
            "toxic_trait": "I'll threat-model a to-do app",
            "excited_about": "the face someone makes when they rotate their first key",
        },
        "builder_title": "Security person catching keys before strangers do",
    },
    {
        "id": "p_clara",
        "name": "Clara Nguyen",
        "school": "Michigan",
        "avatar": "koda",
        "skills": [S("Product management", "expert"), S("Sales / BD"), S("Finance")],
        "missing": ["Frontend", "Backend", "Visual design"],
        "want_to_build": "Something that helps a tiny brand find its first hundred real customers instead of its first thousand followers.",
        "commitment": "cofounder",
        "experience": "founded",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who called eleven strangers during the hackathon and got four yeses",
            "toxic_trait": "I'll ask who's paying for this in minute one",
            "excited_about": "the first customer who wasn't a friend",
        },
        "builder_title": "PM hunting a tiny brand's first hundred customers",
    },
    {
        "id": "p_hana",
        "name": "Hana Kim",
        "school": "Wellesley",
        "avatar": "wren",
        "skills": [S("Frontend", "expert"), S("Visual design"), S("UX research")],
        "missing": ["Backend", "ML / AI", "Data"],
        "want_to_build": "A way to turn any lecture recording into problems you can argue about with a friend.",
        "commitment": "side_project",
        "experience": "first_hackathon",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who rebuilds the UI at hour eighteen because it 'felt wrong'",
            "toxic_trait": "I'll make it pretty before it works",
            "excited_about": "the moment a hard idea suddenly costs nothing to hold",
        },
        "builder_title": "Frontend person turning lectures into arguments",
    },
    {
        "id": "p_raj",
        "name": "Raj Patel",
        "school": "Stanford",
        "avatar": "nova",
        "skills": [S("ML / AI", "expert"), S("Backend", "expert"), S("Fundraising")],
        "missing": ["Product design", "Marketing / Growth"],
        "want_to_build": "An agent that reads a company's own documents and stops answering when it doesn't know.",
        "commitment": "cofounder",
        "experience": "founded",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who is already talking about the seed round",
            "toxic_trait": "I'll say 'we should just raise' about a class project",
            "excited_about": "retrieval that admits when it has nothing",
        },
        "builder_title": "ML founder building agents that say I don't know",
    },
    {
        "id": "p_noor",
        "name": "Noor Al-Rashid",
        "school": "Harvard",
        "avatar": "juno",
        "skills": [S("Product design", "expert"), S("Frontend"), S("Community")],
        "missing": ["Backend", "Data", "ML / AI"],
        "want_to_build": "Small rooms online that expire unless the people in them actually show up.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "3-4",
        "prompts": {
            "hackathon_person": "...who somehow gets the quiet person on the team talking",
            "toxic_trait": "I'll add one more onboarding screen. Just one.",
            "excited_about": "group chats that die on purpose",
        },
        "builder_title": "Designer building rooms that expire on purpose",
    },
    {
        "id": "p_bram",
        "name": "Bram Visser",
        "school": "Olin",
        "avatar": "pixel",
        "skills": [S("Mobile (Android)", "expert"), S("Backend"), S("DevOps / Infra")],
        "missing": ["Visual design", "Product design", "Marketing / Growth"],
        "want_to_build": "An offline-first app for field researchers who lose signal for three days at a time.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who turns off the wifi to prove the demo still works",
            "toxic_trait": "I'll optimize for a phone nobody on the team owns",
            "excited_about": "sync conflicts, which are just philosophy with timestamps",
        },
        "builder_title": "Android dev building for places with no signal",
    },
    {
        "id": "p_sarah",
        "name": "Sarah Chen",
        "school": "Harvard",
        "avatar": "juno",
        "skills": [S("Product design", "expert"), S("Community"), S("UX research")],
        "missing": ["Backend", "Data"],
        "want_to_build": "Small social tools that make neighbors and friends actually show up for each other. Group chats that expire, plans that stick.",
        "commitment": "side_project",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who has a paper prototype before anyone opens a laptop",
            "toxic_trait": "I will redo the onboarding the night before demos",
            "excited_about": "the moment a stranger uses the thing without being told how",
        },
        "builder_title": "Designer building small tools that make people show up",
    },
    {
        "id": "p_leo",
        "name": "Leo Park",
        "school": "BU",
        "avatar": "pixel",
        "skills": [S("Mobile (iOS)", "expert"), S("Frontend"), S("Product design", "learning")],
        "missing": ["Backend", "Marketing / Growth"],
        "want_to_build": "Campus apps people actually open. Dining, events, laundry, starting with my own dorm.",
        "commitment": "hackathon",
        "experience": "shipped",
        "team_size": "2",
        "prompts": {
            "hackathon_person": "...who has it on TestFlight before the team has a name",
            "toxic_trait": "I'll ship to my dorm before I ship to you",
            "excited_about": "apps with exactly one screen",
        },
        "builder_title": "iOS dev building campus apps one dorm at a time",
    },
    {
        "id": "p_jordan",
        "name": "Jordan Rivera",
        "school": "Northeastern",
        "avatar": "ember",
        "skills": [S("Marketing / Growth", "expert"), S("Sales / BD"), S("Writing / Content")],
        "missing": ["Frontend", "Backend"],
        "want_to_build": "Consumer apps built by students that get a real first hundred users. I'll find the people if you build the thing.",
        "commitment": "cofounder",
        "experience": "founded",
        "team_size": "3-4",
        "prompts": {
            "hackathon_person": "...who has 40 people on a waitlist before the repo exists",
            "toxic_trait": "I'll say 'let's just ship it' about things that don't work yet",
            "excited_about": "the first user who isn't a friend",
        },
        "builder_title": "Growth person who finds the first hundred users",
    },
]
